// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: services/secure_shell/v2/secure_shell.proto

package secure_shell

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetUserKeyResponse) Reset() {
	*x = GetUserKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_secure_shell_v2_secure_shell_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserKeyResponse) ProtoMessage() {}

func (x *GetUserKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_secure_shell_v2_secure_shell_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserKeyResponse.ProtoReflect.Descriptor instead.
func (*GetUserKeyResponse) Descriptor() ([]byte, []int) {
	return file_services_secure_shell_v2_secure_shell_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserKeyResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

var File_services_secure_shell_v2_secure_shell_proto protoreflect.FileDescriptor

var file_services_secure_shell_v2_secure_shell_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2f, 0x76, 0x32, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x65, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x70,
	0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x32, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x32, 0x77, 0x0a, 0x17, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x34, 0x2e, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f,
	0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x51, 0x5a,
	0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66,
	0x35, 0x33, 0x2f, 0x70, 0x68, 0x6f, 0x65, 0x6e, 0x69, 0x78, 0x2d, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x2f, 0x76, 0x32, 0x3b, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_secure_shell_v2_secure_shell_proto_rawDescOnce sync.Once
	file_services_secure_shell_v2_secure_shell_proto_rawDescData = file_services_secure_shell_v2_secure_shell_proto_rawDesc
)

func file_services_secure_shell_v2_secure_shell_proto_rawDescGZIP() []byte {
	file_services_secure_shell_v2_secure_shell_proto_rawDescOnce.Do(func() {
		file_services_secure_shell_v2_secure_shell_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_secure_shell_v2_secure_shell_proto_rawDescData)
	})
	return file_services_secure_shell_v2_secure_shell_proto_rawDescData
}

var file_services_secure_shell_v2_secure_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_services_secure_shell_v2_secure_shell_proto_goTypes = []interface{}{
	(*GetUserKeyResponse)(nil), // 0: pga.api.services.secure_shell.v2.GetUserKeyResponse
	(*emptypb.Empty)(nil),      // 1: google.protobuf.Empty
}
var file_services_secure_shell_v2_secure_shell_proto_depIdxs = []int32{
	1, // 0: pga.api.services.secure_shell.v2.AgentSecureShellService.GetUserKey:input_type -> google.protobuf.Empty
	0, // 1: pga.api.services.secure_shell.v2.AgentSecureShellService.GetUserKey:output_type -> pga.api.services.secure_shell.v2.GetUserKeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_secure_shell_v2_secure_shell_proto_init() }
func file_services_secure_shell_v2_secure_shell_proto_init() {
	if File_services_secure_shell_v2_secure_shell_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_secure_shell_v2_secure_shell_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_secure_shell_v2_secure_shell_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_secure_shell_v2_secure_shell_proto_goTypes,
		DependencyIndexes: file_services_secure_shell_v2_secure_shell_proto_depIdxs,
		MessageInfos:      file_services_secure_shell_v2_secure_shell_proto_msgTypes,
	}.Build()
	File_services_secure_shell_v2_secure_shell_proto = out.File
	file_services_secure_shell_v2_secure_shell_proto_rawDesc = nil
	file_services_secure_shell_v2_secure_shell_proto_goTypes = nil
	file_services_secure_shell_v2_secure_shell_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AgentSecureShellServiceClient is the client API for AgentSecureShellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentSecureShellServiceClient interface {
	GetUserKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUserKeyResponse, error)
}

type agentSecureShellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentSecureShellServiceClient(cc grpc.ClientConnInterface) AgentSecureShellServiceClient {
	return &agentSecureShellServiceClient{cc}
}

func (c *agentSecureShellServiceClient) GetUserKey(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetUserKeyResponse, error) {
	out := new(GetUserKeyResponse)
	err := c.cc.Invoke(ctx, "/pga.api.services.secure_shell.v2.AgentSecureShellService/GetUserKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentSecureShellServiceServer is the server API for AgentSecureShellService service.
type AgentSecureShellServiceServer interface {
	GetUserKey(context.Context, *emptypb.Empty) (*GetUserKeyResponse, error)
}

// UnimplementedAgentSecureShellServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAgentSecureShellServiceServer struct {
}

func (*UnimplementedAgentSecureShellServiceServer) GetUserKey(context.Context, *emptypb.Empty) (*GetUserKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserKey not implemented")
}

func RegisterAgentSecureShellServiceServer(s *grpc.Server, srv AgentSecureShellServiceServer) {
	s.RegisterService(&_AgentSecureShellService_serviceDesc, srv)
}

func _AgentSecureShellService_GetUserKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentSecureShellServiceServer).GetUserKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pga.api.services.secure_shell.v2.AgentSecureShellService/GetUserKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentSecureShellServiceServer).GetUserKey(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentSecureShellService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pga.api.services.secure_shell.v2.AgentSecureShellService",
	HandlerType: (*AgentSecureShellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserKey",
			Handler:    _AgentSecureShellService_GetUserKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/secure_shell/v2/secure_shell.proto",
}
