// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: types/v2/agent.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InetFamily int32

const (
	InetFamily_AF_UNSPECIFIED InetFamily = 0
	InetFamily_AF_INET        InetFamily = 2
	InetFamily_AF_INET6       InetFamily = 10
)

// Enum value maps for InetFamily.
var (
	InetFamily_name = map[int32]string{
		0:  "AF_UNSPECIFIED",
		2:  "AF_INET",
		10: "AF_INET6",
	}
	InetFamily_value = map[string]int32{
		"AF_UNSPECIFIED": 0,
		"AF_INET":        2,
		"AF_INET6":       10,
	}
)

func (x InetFamily) Enum() *InetFamily {
	p := new(InetFamily)
	*p = x
	return p
}

func (x InetFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InetFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_types_v2_agent_proto_enumTypes[0].Descriptor()
}

func (InetFamily) Type() protoreflect.EnumType {
	return &file_types_v2_agent_proto_enumTypes[0]
}

func (x InetFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InetFamily.Descriptor instead.
func (InetFamily) EnumDescriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{0}
}

type RouteScope int32

const (
	RouteScope_SCOPE_UNIVERSE RouteScope = 0
	RouteScope_SCOPE_SITE     RouteScope = 200
	RouteScope_SCOPE_LINK     RouteScope = 253
	RouteScope_SCOPE_HOST     RouteScope = 254
	RouteScope_SCOPE_NOWHERE  RouteScope = 255
)

// Enum value maps for RouteScope.
var (
	RouteScope_name = map[int32]string{
		0:   "SCOPE_UNIVERSE",
		200: "SCOPE_SITE",
		253: "SCOPE_LINK",
		254: "SCOPE_HOST",
		255: "SCOPE_NOWHERE",
	}
	RouteScope_value = map[string]int32{
		"SCOPE_UNIVERSE": 0,
		"SCOPE_SITE":     200,
		"SCOPE_LINK":     253,
		"SCOPE_HOST":     254,
		"SCOPE_NOWHERE":  255,
	}
)

func (x RouteScope) Enum() *RouteScope {
	p := new(RouteScope)
	*p = x
	return p
}

func (x RouteScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteScope) Descriptor() protoreflect.EnumDescriptor {
	return file_types_v2_agent_proto_enumTypes[1].Descriptor()
}

func (RouteScope) Type() protoreflect.EnumType {
	return &file_types_v2_agent_proto_enumTypes[1]
}

func (x RouteScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteScope.Descriptor instead.
func (RouteScope) EnumDescriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1}
}

type AgentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  string              `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	IsLocked bool                `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	Features *AgentInfo_Features `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *AgentInfo) GetFeatures() *AgentInfo_Features {
	if x != nil {
		return x.Features
	}
	return nil
}

type GuestInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uname        *GuestInfo_Utsname       `protobuf:"bytes,1,opt,name=uname,proto3" json:"uname,omitempty"`
	Uptime       int64                    `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Loadavg      *GuestInfo_LoadAverage   `protobuf:"bytes,3,opt,name=loadavg,proto3" json:"loadavg,omitempty"`
	Mem          *GuestInfo_MemStat       `protobuf:"bytes,4,opt,name=mem,proto3" json:"mem,omitempty"`
	Swap         *GuestInfo_SwapStat      `protobuf:"bytes,5,opt,name=swap,proto3" json:"swap,omitempty"`
	Users        []*GuestInfo_LoggedUser  `protobuf:"bytes,6,rep,name=users,proto3" json:"users,omitempty"`
	BlockDevices []*GuestInfo_BlockDevice `protobuf:"bytes,7,rep,name=block_devices,json=blockDevices,proto3" json:"block_devices,omitempty"`
}

func (x *GuestInfo) Reset() {
	*x = GuestInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestInfo) ProtoMessage() {}

func (x *GuestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestInfo.ProtoReflect.Descriptor instead.
func (*GuestInfo) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GuestInfo) GetUname() *GuestInfo_Utsname {
	if x != nil {
		return x.Uname
	}
	return nil
}

func (x *GuestInfo) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *GuestInfo) GetLoadavg() *GuestInfo_LoadAverage {
	if x != nil {
		return x.Loadavg
	}
	return nil
}

func (x *GuestInfo) GetMem() *GuestInfo_MemStat {
	if x != nil {
		return x.Mem
	}
	return nil
}

func (x *GuestInfo) GetSwap() *GuestInfo_SwapStat {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *GuestInfo) GetUsers() []*GuestInfo_LoggedUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GuestInfo) GetBlockDevices() []*GuestInfo_BlockDevice {
	if x != nil {
		return x.BlockDevices
	}
	return nil
}

type RouteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkIndex int32      `protobuf:"varint,1,opt,name=link_index,json=linkIndex,proto3" json:"link_index,omitempty"`
	LinkName  string     `protobuf:"bytes,2,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`
	Scope     RouteScope `protobuf:"varint,3,opt,name=scope,proto3,enum=pga.api.types.v2.RouteScope" json:"scope,omitempty"`
	Dst       string     `protobuf:"bytes,4,opt,name=dst,proto3" json:"dst,omitempty"`
	Src       string     `protobuf:"bytes,5,opt,name=src,proto3" json:"src,omitempty"`
	Gw        string     `protobuf:"bytes,6,opt,name=gw,proto3" json:"gw,omitempty"`
	Table     int32      `protobuf:"varint,7,opt,name=table,proto3" json:"table,omitempty"`
}

func (x *RouteInfo) Reset() {
	*x = RouteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo) ProtoMessage() {}

func (x *RouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo.ProtoReflect.Descriptor instead.
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RouteInfo) GetLinkIndex() int32 {
	if x != nil {
		return x.LinkIndex
	}
	return 0
}

func (x *RouteInfo) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *RouteInfo) GetScope() RouteScope {
	if x != nil {
		return x.Scope
	}
	return RouteScope_SCOPE_UNIVERSE
}

func (x *RouteInfo) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *RouteInfo) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *RouteInfo) GetGw() string {
	if x != nil {
		return x.Gw
	}
	return ""
}

func (x *RouteInfo) GetTable() int32 {
	if x != nil {
		return x.Table
	}
	return 0
}

type InterfaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name   string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HwAddr string   `protobuf:"bytes,3,opt,name=hw_addr,json=hwAddr,proto3" json:"hw_addr,omitempty"`
	Flags  uint32   `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	MTU    int32    `protobuf:"varint,5,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Addrs  []string `protobuf:"bytes,6,rep,name=addrs,proto3" json:"addrs,omitempty"`
}

func (x *InterfaceInfo) Reset() {
	*x = InterfaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceInfo) ProtoMessage() {}

func (x *InterfaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceInfo.ProtoReflect.Descriptor instead.
func (*InterfaceInfo) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InterfaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceInfo) GetHwAddr() string {
	if x != nil {
		return x.HwAddr
	}
	return ""
}

func (x *InterfaceInfo) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *InterfaceInfo) GetMTU() int32 {
	if x != nil {
		return x.MTU
	}
	return 0
}

func (x *InterfaceInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

type FileStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode      uint32          `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir     bool            `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Owner     *FileStat_Owner `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Group     *FileStat_Group `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	SizeBytes int64           `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
}

func (x *FileStat) Reset() {
	*x = FileStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat) ProtoMessage() {}

func (x *FileStat) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStat.ProtoReflect.Descriptor instead.
func (*FileStat) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{4}
}

func (x *FileStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileStat) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileStat) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileStat) GetOwner() *FileStat_Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *FileStat) GetGroup() *FileStat_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *FileStat) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type AgentInfo_Features struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LegacyMode bool   `protobuf:"varint,1,opt,name=legacy_mode,json=legacyMode,proto3" json:"legacy_mode,omitempty"`
	SerialPort string `protobuf:"bytes,2,opt,name=serial_port,json=serialPort,proto3" json:"serial_port,omitempty"`
	WithoutSSH bool   `protobuf:"varint,3,opt,name=without_ssh,json=withoutSsh,proto3" json:"without_ssh,omitempty"`
	WithoutTCP bool   `protobuf:"varint,4,opt,name=without_tcp,json=withoutTcp,proto3" json:"without_tcp,omitempty"`
}

func (x *AgentInfo_Features) Reset() {
	*x = AgentInfo_Features{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentInfo_Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo_Features) ProtoMessage() {}

func (x *AgentInfo_Features) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo_Features.ProtoReflect.Descriptor instead.
func (*AgentInfo_Features) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AgentInfo_Features) GetLegacyMode() bool {
	if x != nil {
		return x.LegacyMode
	}
	return false
}

func (x *AgentInfo_Features) GetSerialPort() string {
	if x != nil {
		return x.SerialPort
	}
	return ""
}

func (x *AgentInfo_Features) GetWithoutSSH() bool {
	if x != nil {
		return x.WithoutSSH
	}
	return false
}

func (x *AgentInfo_Features) GetWithoutTCP() bool {
	if x != nil {
		return x.WithoutTCP
	}
	return false
}

type GuestInfo_Utsname struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sysname    string `protobuf:"bytes,1,opt,name=sysname,proto3" json:"sysname,omitempty"`
	Nodename   string `protobuf:"bytes,2,opt,name=nodename,proto3" json:"nodename,omitempty"`
	Release    string `protobuf:"bytes,3,opt,name=release,proto3" json:"release,omitempty"`
	Version    string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Machine    string `protobuf:"bytes,5,opt,name=machine,proto3" json:"machine,omitempty"`
	Domainname string `protobuf:"bytes,6,opt,name=domainname,proto3" json:"domainname,omitempty"`
}

func (x *GuestInfo_Utsname) Reset() {
	*x = GuestInfo_Utsname{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestInfo_Utsname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestInfo_Utsname) ProtoMessage() {}

func (x *GuestInfo_Utsname) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestInfo_Utsname.ProtoReflect.Descriptor instead.
func (*GuestInfo_Utsname) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GuestInfo_Utsname) GetSysname() string {
	if x != nil {
		return x.Sysname
	}
	return ""
}

func (x *GuestInfo_Utsname) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

func (x *GuestInfo_Utsname) GetRelease() string {
	if x != nil {
		return x.Release
	}
	return ""
}

func (x *GuestInfo_Utsname) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GuestInfo_Utsname) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *GuestInfo_Utsname) GetDomainname() string {
	if x != nil {
		return x.Domainname
	}
	return ""
}

type GuestInfo_LoadAverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One     float64 `protobuf:"fixed64,1,opt,name=one,proto3" json:"one,omitempty"`
	Five    float64 `protobuf:"fixed64,2,opt,name=five,proto3" json:"five,omitempty"`
	Fifteen float64 `protobuf:"fixed64,3,opt,name=fifteen,proto3" json:"fifteen,omitempty"`
}

func (x *GuestInfo_LoadAverage) Reset() {
	*x = GuestInfo_LoadAverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestInfo_LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestInfo_LoadAverage) ProtoMessage() {}

func (x *GuestInfo_LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestInfo_LoadAverage.ProtoReflect.Descriptor instead.
func (*GuestInfo_LoadAverage) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GuestInfo_LoadAverage) GetOne() float64 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *GuestInfo_LoadAverage) GetFive() float64 {
	if x != nil {
		return x.Five
	}
	return 0
}

func (x *GuestInfo_LoadAverage) GetFifteen() float64 {
	if x != nil {
		return x.Fifteen
	}
	return 0
}

type GuestInfo_MemStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total     uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Free      uint64 `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Buffers   uint64 `protobuf:"varint,3,opt,name=buffers,proto3" json:"buffers,omitempty"`
	Cached    uint64 `protobuf:"varint,4,opt,name=cached,proto3" json:"cached,omitempty"`
	FreeTotal uint64 `protobuf:"varint,5,opt,name=free_total,json=freeTotal,proto3" json:"free_total,omitempty"`
}

func (x *GuestInfo_MemStat) Reset() {
	*x = GuestInfo_MemStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestInfo_MemStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestInfo_MemStat) ProtoMessage() {}

func (x *GuestInfo_MemStat) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestInfo_MemStat.ProtoReflect.Descriptor instead.
func (*GuestInfo_MemStat) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GuestInfo_MemStat) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GuestInfo_MemStat) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *GuestInfo_MemStat) GetBuffers() uint64 {
	if x != nil {
		return x.Buffers
	}
	return 0
}

func (x *GuestInfo_MemStat) GetCached() uint64 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *GuestInfo_MemStat) GetFreeTotal() uint64 {
	if x != nil {
		return x.FreeTotal
	}
	return 0
}

type GuestInfo_SwapStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Free  uint64 `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
}

func (x *GuestInfo_SwapStat) Reset() {
	*x = GuestInfo_SwapStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestInfo_SwapStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestInfo_SwapStat) ProtoMessage() {}

func (x *GuestInfo_SwapStat) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestInfo_SwapStat.ProtoReflect.Descriptor instead.
func (*GuestInfo_SwapStat) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1, 3}
}

func (x *GuestInfo_SwapStat) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GuestInfo_SwapStat) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

type GuestInfo_LoggedUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Device    string `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Host      string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	LoginTime int64  `protobuf:"varint,4,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
}

func (x *GuestInfo_LoggedUser) Reset() {
	*x = GuestInfo_LoggedUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestInfo_LoggedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestInfo_LoggedUser) ProtoMessage() {}

func (x *GuestInfo_LoggedUser) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestInfo_LoggedUser.ProtoReflect.Descriptor instead.
func (*GuestInfo_LoggedUser) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1, 4}
}

func (x *GuestInfo_LoggedUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuestInfo_LoggedUser) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *GuestInfo_LoggedUser) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GuestInfo_LoggedUser) GetLoginTime() int64 {
	if x != nil {
		return x.LoginTime
	}
	return 0
}

type GuestInfo_BlockDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsMounted   bool   `protobuf:"varint,2,opt,name=is_mounted,json=isMounted,proto3" json:"is_mounted,omitempty"`
	MountPoint  string `protobuf:"bytes,3,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	SizeTotal   int64  `protobuf:"varint,4,opt,name=size_total,json=sizeTotal,proto3" json:"size_total,omitempty"`
	SizeUsed    int64  `protobuf:"varint,5,opt,name=size_used,json=sizeUsed,proto3" json:"size_used,omitempty"`
	SizeAvail   int64  `protobuf:"varint,6,opt,name=size_avail,json=sizeAvail,proto3" json:"size_avail,omitempty"`
	InodesTotal int64  `protobuf:"varint,7,opt,name=inodes_total,json=inodesTotal,proto3" json:"inodes_total,omitempty"`
	InodesUsed  int64  `protobuf:"varint,8,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	InodesAvail int64  `protobuf:"varint,9,opt,name=inodes_avail,json=inodesAvail,proto3" json:"inodes_avail,omitempty"`
}

func (x *GuestInfo_BlockDevice) Reset() {
	*x = GuestInfo_BlockDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuestInfo_BlockDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestInfo_BlockDevice) ProtoMessage() {}

func (x *GuestInfo_BlockDevice) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestInfo_BlockDevice.ProtoReflect.Descriptor instead.
func (*GuestInfo_BlockDevice) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{1, 5}
}

func (x *GuestInfo_BlockDevice) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GuestInfo_BlockDevice) GetIsMounted() bool {
	if x != nil {
		return x.IsMounted
	}
	return false
}

func (x *GuestInfo_BlockDevice) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *GuestInfo_BlockDevice) GetSizeTotal() int64 {
	if x != nil {
		return x.SizeTotal
	}
	return 0
}

func (x *GuestInfo_BlockDevice) GetSizeUsed() int64 {
	if x != nil {
		return x.SizeUsed
	}
	return 0
}

func (x *GuestInfo_BlockDevice) GetSizeAvail() int64 {
	if x != nil {
		return x.SizeAvail
	}
	return 0
}

func (x *GuestInfo_BlockDevice) GetInodesTotal() int64 {
	if x != nil {
		return x.InodesTotal
	}
	return 0
}

func (x *GuestInfo_BlockDevice) GetInodesUsed() int64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

func (x *GuestInfo_BlockDevice) GetInodesAvail() int64 {
	if x != nil {
		return x.InodesAvail
	}
	return 0
}

type FileStat_Owner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID  uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FileStat_Owner) Reset() {
	*x = FileStat_Owner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStat_Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat_Owner) ProtoMessage() {}

func (x *FileStat_Owner) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStat_Owner.ProtoReflect.Descriptor instead.
func (*FileStat_Owner) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{4, 0}
}

func (x *FileStat_Owner) GetUID() uint32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *FileStat_Owner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FileStat_Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GID  uint32 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FileStat_Group) Reset() {
	*x = FileStat_Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStat_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStat_Group) ProtoMessage() {}

func (x *FileStat_Group) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStat_Group.ProtoReflect.Descriptor instead.
func (*FileStat_Group) Descriptor() ([]byte, []int) {
	return file_types_v2_agent_proto_rawDescGZIP(), []int{4, 1}
}

func (x *FileStat_Group) GetGID() uint32 {
	if x != nil {
		return x.GID
	}
	return 0
}

func (x *FileStat_Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_types_v2_agent_proto protoreflect.FileDescriptor

var file_types_v2_agent_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x22, 0x95, 0x02, 0x0a, 0x09, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x40, 0x0a,
	0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x76, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x46, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x1a,
	0x8e, 0x01, 0x0a, 0x08, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x53, 0x73, 0x68, 0x12,
	0x1f, 0x0a, 0x0b, 0x77, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x5f, 0x74, 0x63, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x54, 0x63, 0x70,
	0x22, 0xed, 0x09, 0x0a, 0x09, 0x47, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39,
	0x0a, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32,
	0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x74, 0x73, 0x6e, 0x61,
	0x6d, 0x65, 0x52, 0x05, 0x75, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x41, 0x0a, 0x07, 0x6c, 0x6f, 0x61, 0x64, 0x61, 0x76, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6c, 0x6f, 0x61,
	0x64, 0x61, 0x76, 0x67, 0x12, 0x35, 0x0a, 0x03, 0x6d, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x52, 0x03, 0x6d, 0x65, 0x6d, 0x12, 0x38, 0x0a, 0x04, 0x73,
	0x77, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x67, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x04, 0x73, 0x77, 0x61, 0x70, 0x12, 0x3c, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x4c, 0x0a, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x67, 0x61,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x47, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x1a, 0xad, 0x01, 0x0a, 0x07, 0x55, 0x74, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x79, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x79, 0x73, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x6e, 0x61, 0x6d,
	0x65, 0x1a, 0x4d, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6f,
	0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x66, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e,
	0x1a, 0x84, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x66, 0x72, 0x65, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x63, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x65, 0x65,
	0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x66, 0x72,
	0x65, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x1a, 0x34, 0x0a, 0x08, 0x53, 0x77, 0x61, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x65,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72, 0x65, 0x65, 0x1a, 0x6b, 0x0a,
	0x0a, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0xa3, 0x02, 0x0a, 0x0b, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x69, 0x7a, 0x65, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69,
	0x7a, 0x65, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x73, 0x69, 0x7a, 0x65, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x69, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x22, 0xc5, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x63,
	0x6f, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x67, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x72, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x67, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x67, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x0d, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x77, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x66, 0x6c,
	0x61, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6d, 0x74, 0x75, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x22, 0xb6, 0x02, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x12, 0x36, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x36, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x70, 0x67, 0x61, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76,
	0x32, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a,
	0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x1a, 0x2d, 0x0a, 0x05, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x2d, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x67, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x2a, 0x3b, 0x0a, 0x0a, 0x49, 0x6e, 0x65, 0x74, 0x46, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x46, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x46, 0x5f, 0x49, 0x4e, 0x45,
	0x54, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x46, 0x5f, 0x49, 0x4e, 0x45, 0x54, 0x36, 0x10,
	0x0a, 0x2a, 0x67, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x0e, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x49, 0x56, 0x45, 0x52, 0x53,
	0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0a, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f, 0x53, 0x49, 0x54,
	0x45, 0x10, 0xc8, 0x01, 0x12, 0x0f, 0x0a, 0x0a, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f, 0x4c, 0x49,
	0x4e, 0x4b, 0x10, 0xfd, 0x01, 0x12, 0x0f, 0x0a, 0x0a, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f, 0x48,
	0x4f, 0x53, 0x54, 0x10, 0xfe, 0x01, 0x12, 0x12, 0x0a, 0x0d, 0x53, 0x43, 0x4f, 0x50, 0x45, 0x5f,
	0x4e, 0x4f, 0x57, 0x48, 0x45, 0x52, 0x45, 0x10, 0xff, 0x01, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66, 0x35, 0x33, 0x2f,
	0x70, 0x68, 0x6f, 0x65, 0x6e, 0x69, 0x78, 0x2d, 0x67, 0x75, 0x65, 0x73, 0x74, 0x2d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32,
	0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_v2_agent_proto_rawDescOnce sync.Once
	file_types_v2_agent_proto_rawDescData = file_types_v2_agent_proto_rawDesc
)

func file_types_v2_agent_proto_rawDescGZIP() []byte {
	file_types_v2_agent_proto_rawDescOnce.Do(func() {
		file_types_v2_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_v2_agent_proto_rawDescData)
	})
	return file_types_v2_agent_proto_rawDescData
}

var file_types_v2_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_types_v2_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_types_v2_agent_proto_goTypes = []interface{}{
	(InetFamily)(0),               // 0: pga.api.types.v2.InetFamily
	(RouteScope)(0),               // 1: pga.api.types.v2.RouteScope
	(*AgentInfo)(nil),             // 2: pga.api.types.v2.AgentInfo
	(*GuestInfo)(nil),             // 3: pga.api.types.v2.GuestInfo
	(*RouteInfo)(nil),             // 4: pga.api.types.v2.RouteInfo
	(*InterfaceInfo)(nil),         // 5: pga.api.types.v2.InterfaceInfo
	(*FileStat)(nil),              // 6: pga.api.types.v2.FileStat
	(*AgentInfo_Features)(nil),    // 7: pga.api.types.v2.AgentInfo.Features
	(*GuestInfo_Utsname)(nil),     // 8: pga.api.types.v2.GuestInfo.Utsname
	(*GuestInfo_LoadAverage)(nil), // 9: pga.api.types.v2.GuestInfo.LoadAverage
	(*GuestInfo_MemStat)(nil),     // 10: pga.api.types.v2.GuestInfo.MemStat
	(*GuestInfo_SwapStat)(nil),    // 11: pga.api.types.v2.GuestInfo.SwapStat
	(*GuestInfo_LoggedUser)(nil),  // 12: pga.api.types.v2.GuestInfo.LoggedUser
	(*GuestInfo_BlockDevice)(nil), // 13: pga.api.types.v2.GuestInfo.BlockDevice
	(*FileStat_Owner)(nil),        // 14: pga.api.types.v2.FileStat.Owner
	(*FileStat_Group)(nil),        // 15: pga.api.types.v2.FileStat.Group
}
var file_types_v2_agent_proto_depIdxs = []int32{
	7,  // 0: pga.api.types.v2.AgentInfo.features:type_name -> pga.api.types.v2.AgentInfo.Features
	8,  // 1: pga.api.types.v2.GuestInfo.uname:type_name -> pga.api.types.v2.GuestInfo.Utsname
	9,  // 2: pga.api.types.v2.GuestInfo.loadavg:type_name -> pga.api.types.v2.GuestInfo.LoadAverage
	10, // 3: pga.api.types.v2.GuestInfo.mem:type_name -> pga.api.types.v2.GuestInfo.MemStat
	11, // 4: pga.api.types.v2.GuestInfo.swap:type_name -> pga.api.types.v2.GuestInfo.SwapStat
	12, // 5: pga.api.types.v2.GuestInfo.users:type_name -> pga.api.types.v2.GuestInfo.LoggedUser
	13, // 6: pga.api.types.v2.GuestInfo.block_devices:type_name -> pga.api.types.v2.GuestInfo.BlockDevice
	1,  // 7: pga.api.types.v2.RouteInfo.scope:type_name -> pga.api.types.v2.RouteScope
	14, // 8: pga.api.types.v2.FileStat.owner:type_name -> pga.api.types.v2.FileStat.Owner
	15, // 9: pga.api.types.v2.FileStat.group:type_name -> pga.api.types.v2.FileStat.Group
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_types_v2_agent_proto_init() }
func file_types_v2_agent_proto_init() {
	if File_types_v2_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_v2_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentInfo_Features); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestInfo_Utsname); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestInfo_LoadAverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestInfo_MemStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestInfo_SwapStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestInfo_LoggedUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuestInfo_BlockDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStat_Owner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_agent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStat_Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_v2_agent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_v2_agent_proto_goTypes,
		DependencyIndexes: file_types_v2_agent_proto_depIdxs,
		EnumInfos:         file_types_v2_agent_proto_enumTypes,
		MessageInfos:      file_types_v2_agent_proto_msgTypes,
	}.Build()
	File_types_v2_agent_proto = out.File
	file_types_v2_agent_proto_rawDesc = nil
	file_types_v2_agent_proto_goTypes = nil
	file_types_v2_agent_proto_depIdxs = nil
}
